//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.17 at 08:03:48 PM CEST 
//


package org.purl.atom.ns_;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for entryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="title" type="{http://purl.org/atom/ns#}contentType"/>
 *         &lt;element name="author" type="{http://purl.org/atom/ns#}authorType"/>
 *         &lt;element name="id" type="{http://purl.org/atom/ns#}stringType"/>
 *         &lt;element name="modified" type="{http://purl.org/atom/ns#}dateTimeType"/>
 *         &lt;element name="issued" type="{http://purl.org/atom/ns#}dateTimeType"/>
 *         &lt;element name="created" type="{http://purl.org/atom/ns#}dateTimeType"/>
 *         &lt;element name="summary" type="{http://purl.org/atom/ns#}contentType"/>
 *         &lt;element name="generator" type="{http://purl.org/atom/ns#}generatorType"/>
 *         &lt;element name="link" type="{http://purl.org/atom/ns#}linkType"/>
 *         &lt;element name="contributor" type="{http://purl.org/atom/ns#}authorType"/>
 *         &lt;element name="content" type="{http://purl.org/atom/ns#}contentType"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://purl.org/atom/ns#}commonAttributes"/>
 *       &lt;attribute name="version" use="required" type="{http://purl.org/atom/ns#}versionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entryType", propOrder = {
    "titleOrAuthorOrId"
})
public class EntryType {

    @XmlElementRefs({
        @XmlElementRef(name = "generator", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class),
        @XmlElementRef(name = "author", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class),
        @XmlElementRef(name = "title", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class),
        @XmlElementRef(name = "link", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class),
        @XmlElementRef(name = "id", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class),
        @XmlElementRef(name = "created", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class),
        @XmlElementRef(name = "modified", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class),
        @XmlElementRef(name = "contributor", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class),
        @XmlElementRef(name = "summary", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class),
        @XmlElementRef(name = "content", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class),
        @XmlElementRef(name = "issued", namespace = "http://purl.org/atom/ns#", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> titleOrAuthorOrId;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;

    /**
     * Gets the value of the titleOrAuthorOrId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleOrAuthorOrId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleOrAuthorOrId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link GeneratorType }{@code >}
     * {@link JAXBElement }{@code <}{@link AuthorType }{@code >}
     * {@link JAXBElement }{@code <}{@link ContentType }{@code >}
     * {@link JAXBElement }{@code <}{@link StringType }{@code >}
     * {@link JAXBElement }{@code <}{@link LinkType }{@code >}
     * {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     * {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     * {@link JAXBElement }{@code <}{@link AuthorType }{@code >}
     * {@link JAXBElement }{@code <}{@link ContentType }{@code >}
     * {@link JAXBElement }{@code <}{@link ContentType }{@code >}
     * {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getTitleOrAuthorOrId() {
        if (titleOrAuthorOrId == null) {
            titleOrAuthorOrId = new ArrayList<JAXBElement<?>>();
        }
        return this.titleOrAuthorOrId;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
