//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.17 at 08:03:48 PM CEST 
//


package org.purl.atom.ns_;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.purl.atom.ns_ package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Feed_QNAME = new QName("http://purl.org/atom/ns#", "feed");
    private final static QName _Entry_QNAME = new QName("http://purl.org/atom/ns#", "entry");
    private final static QName _FeedinfoTypeModified_QNAME = new QName("http://purl.org/atom/ns#", "modified");
    private final static QName _FeedinfoTypeInfo_QNAME = new QName("http://purl.org/atom/ns#", "info");
    private final static QName _FeedinfoTypeTagline_QNAME = new QName("http://purl.org/atom/ns#", "tagline");
    private final static QName _FeedinfoTypeGenerator_QNAME = new QName("http://purl.org/atom/ns#", "generator");
    private final static QName _FeedinfoTypeCopyright_QNAME = new QName("http://purl.org/atom/ns#", "copyright");
    private final static QName _FeedinfoTypeContributor_QNAME = new QName("http://purl.org/atom/ns#", "contributor");
    private final static QName _FeedinfoTypeLink_QNAME = new QName("http://purl.org/atom/ns#", "link");
    private final static QName _FeedinfoTypeId_QNAME = new QName("http://purl.org/atom/ns#", "id");
    private final static QName _FeedinfoTypeAuthor_QNAME = new QName("http://purl.org/atom/ns#", "author");
    private final static QName _FeedinfoTypeTitle_QNAME = new QName("http://purl.org/atom/ns#", "title");
    private final static QName _EntryTypeCreated_QNAME = new QName("http://purl.org/atom/ns#", "created");
    private final static QName _EntryTypeIssued_QNAME = new QName("http://purl.org/atom/ns#", "issued");
    private final static QName _EntryTypeSummary_QNAME = new QName("http://purl.org/atom/ns#", "summary");
    private final static QName _EntryTypeContent_QNAME = new QName("http://purl.org/atom/ns#", "content");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.purl.atom.ns_
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link EmailType }
     * 
     */
    public EmailType createEmailType() {
        return new EmailType();
    }

    /**
     * Create an instance of {@link FeedinfoType }
     * 
     */
    public FeedinfoType createFeedinfoType() {
        return new FeedinfoType();
    }

    /**
     * Create an instance of {@link AuthorType }
     * 
     */
    public AuthorType createAuthorType() {
        return new AuthorType();
    }

    /**
     * Create an instance of {@link GeneratorType }
     * 
     */
    public GeneratorType createGeneratorType() {
        return new GeneratorType();
    }

    /**
     * Create an instance of {@link DateTimeType }
     * 
     */
    public DateTimeType createDateTimeType() {
        return new DateTimeType();
    }

    /**
     * Create an instance of {@link FeedType }
     * 
     */
    public FeedType createFeedType() {
        return new FeedType();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link UriType }
     * 
     */
    public UriType createUriType() {
        return new UriType();
    }

    /**
     * Create an instance of {@link StringType }
     * 
     */
    public StringType createStringType() {
        return new StringType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "feed")
    public JAXBElement<FeedType> createFeed(FeedType value) {
        return new JAXBElement<FeedType>(_Feed_QNAME, FeedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "entry")
    public JAXBElement<EntryType> createEntry(EntryType value) {
        return new JAXBElement<EntryType>(_Entry_QNAME, EntryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "modified", scope = FeedinfoType.class)
    public JAXBElement<DateTimeType> createFeedinfoTypeModified(DateTimeType value) {
        return new JAXBElement<DateTimeType>(_FeedinfoTypeModified_QNAME, DateTimeType.class, FeedinfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "info", scope = FeedinfoType.class)
    public JAXBElement<ContentType> createFeedinfoTypeInfo(ContentType value) {
        return new JAXBElement<ContentType>(_FeedinfoTypeInfo_QNAME, ContentType.class, FeedinfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "tagline", scope = FeedinfoType.class)
    public JAXBElement<ContentType> createFeedinfoTypeTagline(ContentType value) {
        return new JAXBElement<ContentType>(_FeedinfoTypeTagline_QNAME, ContentType.class, FeedinfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeneratorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "generator", scope = FeedinfoType.class)
    public JAXBElement<GeneratorType> createFeedinfoTypeGenerator(GeneratorType value) {
        return new JAXBElement<GeneratorType>(_FeedinfoTypeGenerator_QNAME, GeneratorType.class, FeedinfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "copyright", scope = FeedinfoType.class)
    public JAXBElement<ContentType> createFeedinfoTypeCopyright(ContentType value) {
        return new JAXBElement<ContentType>(_FeedinfoTypeCopyright_QNAME, ContentType.class, FeedinfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "contributor", scope = FeedinfoType.class)
    public JAXBElement<AuthorType> createFeedinfoTypeContributor(AuthorType value) {
        return new JAXBElement<AuthorType>(_FeedinfoTypeContributor_QNAME, AuthorType.class, FeedinfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "link", scope = FeedinfoType.class)
    public JAXBElement<LinkType> createFeedinfoTypeLink(LinkType value) {
        return new JAXBElement<LinkType>(_FeedinfoTypeLink_QNAME, LinkType.class, FeedinfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "id", scope = FeedinfoType.class)
    public JAXBElement<UriType> createFeedinfoTypeId(UriType value) {
        return new JAXBElement<UriType>(_FeedinfoTypeId_QNAME, UriType.class, FeedinfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "author", scope = FeedinfoType.class)
    public JAXBElement<AuthorType> createFeedinfoTypeAuthor(AuthorType value) {
        return new JAXBElement<AuthorType>(_FeedinfoTypeAuthor_QNAME, AuthorType.class, FeedinfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "title", scope = FeedinfoType.class)
    public JAXBElement<ContentType> createFeedinfoTypeTitle(ContentType value) {
        return new JAXBElement<ContentType>(_FeedinfoTypeTitle_QNAME, ContentType.class, FeedinfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "modified", scope = EntryType.class)
    public JAXBElement<DateTimeType> createEntryTypeModified(DateTimeType value) {
        return new JAXBElement<DateTimeType>(_FeedinfoTypeModified_QNAME, DateTimeType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeneratorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "generator", scope = EntryType.class)
    public JAXBElement<GeneratorType> createEntryTypeGenerator(GeneratorType value) {
        return new JAXBElement<GeneratorType>(_FeedinfoTypeGenerator_QNAME, GeneratorType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "created", scope = EntryType.class)
    public JAXBElement<DateTimeType> createEntryTypeCreated(DateTimeType value) {
        return new JAXBElement<DateTimeType>(_EntryTypeCreated_QNAME, DateTimeType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "contributor", scope = EntryType.class)
    public JAXBElement<AuthorType> createEntryTypeContributor(AuthorType value) {
        return new JAXBElement<AuthorType>(_FeedinfoTypeContributor_QNAME, AuthorType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "issued", scope = EntryType.class)
    public JAXBElement<DateTimeType> createEntryTypeIssued(DateTimeType value) {
        return new JAXBElement<DateTimeType>(_EntryTypeIssued_QNAME, DateTimeType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "link", scope = EntryType.class)
    public JAXBElement<LinkType> createEntryTypeLink(LinkType value) {
        return new JAXBElement<LinkType>(_FeedinfoTypeLink_QNAME, LinkType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "summary", scope = EntryType.class)
    public JAXBElement<ContentType> createEntryTypeSummary(ContentType value) {
        return new JAXBElement<ContentType>(_EntryTypeSummary_QNAME, ContentType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "content", scope = EntryType.class)
    public JAXBElement<ContentType> createEntryTypeContent(ContentType value) {
        return new JAXBElement<ContentType>(_EntryTypeContent_QNAME, ContentType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "id", scope = EntryType.class)
    public JAXBElement<StringType> createEntryTypeId(StringType value) {
        return new JAXBElement<StringType>(_FeedinfoTypeId_QNAME, StringType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "author", scope = EntryType.class)
    public JAXBElement<AuthorType> createEntryTypeAuthor(AuthorType value) {
        return new JAXBElement<AuthorType>(_FeedinfoTypeAuthor_QNAME, AuthorType.class, EntryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/atom/ns#", name = "title", scope = EntryType.class)
    public JAXBElement<ContentType> createEntryTypeTitle(ContentType value) {
        return new JAXBElement<ContentType>(_FeedinfoTypeTitle_QNAME, ContentType.class, EntryType.class, value);
    }

}
