//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.17 at 08:03:48 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://purl.org/atom/ns#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.purl.atom.ns_;
