all:
	gcc -I /home/batas2/Pobrane/openss7-0.9.2.G/streams-0.9.2.4/include -I /usr/include/strinet -I /usr/include/strxnet -lxnet klient.c -o klient
	gcc -I /home/batas2/Pobrane/openss7-0.9.2.G/streams-0.9.2.4/include -I /usr/include/strinet -I /usr/include/strxnet -lxnet serwer.c -o serwer
clean:
	rm serwer
	rm klient
