######################################################################
# Automatically generated by qmake (2.01a) pt. kwi 2 14:23:43 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyWidget.h modes.cpp
SOURCES += main.cpp modes.cpp MyWidget.cpp
