######################################################################
# Automatically generated by qmake (2.01a) ?r. mar 24 16:49:42 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
