TEMPLATE = app
DESTDIR = dist/Debug/GNU-Linux-x86
TARGET = basic
VERSION = 1.0.0
CONFIG -= debug_and_release app_bundle lib_bundle
CONFIG += debug 
QT = core gui
SOURCES += MyThread.cpp MyWidget.cpp FrameCounter.cpp main.cpp
HEADERS += MyThread.h main.h FrameCounter.h MyWidget.h
FORMS +=
RESOURCES +=
TRANSLATIONS +=
OBJECTS_DIR = build/Debug/GNU-Linux-x86
MOC_DIR = 
RCC_DIR = 
UI_DIR = 
QMAKE_CC = gcc
QMAKE_CXX = g++
DEFINES += 
INCLUDEPATH += 
LIBS += 
